FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /usr/local/project/src

# Copy solution and restore
COPY *.sln ./
COPY Domain/*.csproj ./Domain/
COPY DomainTest/*.csproj ./DomainTest/
COPY Application/*.csproj ./Application/
COPY Infrastructure/*.csproj ./Infrastructure/
RUN dotnet restore

# Copy the entire project
COPY . .

CMD dotnet test --verbosity normal
