services:
    hand:
        image: hand-hand:latest
        volumes:
            - ..:/usr/local/project
        environment:
            DOTNET_ENVIRONMENT: Development
            MongoDB__Host: mongodb
            MongoDB__Port: 27017
            MongoDB__Username: hand
            MongoDB__Password: hand
            MongoDB__Database: hand
            RabbitMQ__Host: rabbitmq
            RabbitMQ__Port: 5672
            RabbitMQ__Username: hand
            RabbitMQ__Password: hand
        depends_on:
            - mongodb
            - rabbitmq

    mongodb:
        image: mongo:8.0.9
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: hand
            MONGO_INITDB_ROOT_PASSWORD: hand
            MONGO_INITDB_DATABASE: hand

    rabbitmq:
        image: rabbitmq:4.1.3-management
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq
        environment:
            RABBITMQ_DEFAULT_USER: hand
            RABBITMQ_DEFAULT_PASS: hand

volumes:
    mongodb-data:
    rabbitmq-data:
