services:
    hand:
        image: hand-hand:latest
        volumes:
            - ..:/usr/local/project
        environment:
            DOTNET_ENVIRONMENT: Development
            MongoDB__Host: mongodb
            MongoDB__Port: 27017
            MongoDB__Username: hand
            MongoDB__Password: hand
            MongoDB__Database: hand
        depends_on:
            - mongodb

    mongodb:
        image: mongo:8.0.9
        volumes:
            - mongodb-data:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: hand
            MONGO_INITDB_ROOT_PASSWORD: hand
            MONGO_INITDB_DATABASE: hand

volumes:
    mongodb-data:
