@Infrastructure_HostAddress = http://0.0.0.0:5260

### Start a new hand
POST {{Infrastructure_HostAddress}}/api/hand
Accept: application/json
Content-Type: application/json

{
    "tableUid": "00000000-0000-0000-0000-000000000000",
    "tableType": "Cash",
    "rules": {
        "game": "NoLimitHoldem",
        "maxSeat": 6,
        "smallBlind": 5,
        "bigBlind": 10
    },
    "table": {
        "positions": {
            "smallBlindSeat": 2,
            "bigBlindSeat": 4,
            "buttonSeat": 6
        },
        "players": [
            {
                "nickname": "alice",
                "seat": 1,
                "stack": 1000
            },
            {
                "nickname": "bobby",
                "seat": 2,
                "stack": 900
            },
            {
                "nickname": "charlie",
                "seat": 6,
                "stack": 800
            }
        ]
    }
}
> {%
    client.global.set("handUid", response.body.uid);
%}

### Submit a player action
POST {{Infrastructure_HostAddress}}/api/hand/{{handUid}}/submit-action/charlie
Accept: application/json
Content-Type: application/json

{
    "Type": "RaiseBy",
    "Amount": 20
}

### Get the hand
GET {{Infrastructure_HostAddress}}/api/hand/{{handUid}}
Accept: application/json

###
